diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=wincred
alias.ch=checkout
alias.branches=branch --format='%(color:yellow)%(refname:short)%(color:reset) - %(contents:subject) %(color:green)(%(committerdate:relative)) [%(authorname)]' --sort=-committerdate
alias.ll=log --oneline
alias.last=log -1 HEAD --stat
alias.br=branch
alias.co=commit
alias.st=status
alias.alias=config --get-regexp ^alias\.
alias.graph=log --all --graph --decorate --oneline
alias.undo=reset --soft HEAD^
alias.rank=shortlog -sn --no-merges
alias.fresh=git add -f  reset --hard HEAD && git clean-f -d
alias.bc=checkout -b
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/SantDiaz/FletesCuyo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.vscode-merge-base=origin/main
branch.main.merge=refs/heads/main
user.name=SantDiaz
user.email=santi.diazok2001@gmail.com
